export const CATEGORIES = [
  // Wiki
  { id: 'adblock',     group: 'Wiki',  icon: '🛡️', name: 'Adblocking / Privacy',    url: 'https://fmhy.net/adblock-vpn-privacy',  desc: 'Ad blockers, VPNs, DNS, browser privacy, tracking protection & more.' },
  { id: 'ai',          group: 'Wiki',  icon: '🤖', name: 'Artificial Intelligence',  url: 'https://fmhy.net/ai',                   desc: 'AI chatbots, image generators, writing tools, coding assistants & research.' },
  { id: 'movies',      group: 'Wiki',  icon: '🎬', name: 'Movies / TV / Anime',      url: 'https://fmhy.net/videopiracy',          desc: 'Stream, download, and torrent movies, TV shows, anime, cartoons & live sports.' },
  { id: 'music',       group: 'Wiki',  icon: '🎵', name: 'Music / Podcasts / Radio', url: 'https://fmhy.net/audiopiracy',          desc: 'Streaming, downloading, and torrenting music, podcasts, and radio.' },
  { id: 'gaming',      group: 'Wiki',  icon: '🎮', name: 'Gaming / Emulation',       url: 'https://fmhy.net/gamingpiracy',         desc: 'Game downloads, emulators, ROMs, mods, and game clients.' },
  { id: 'books',       group: 'Wiki',  icon: '📚', name: 'Books / Comics / Manga',   url: 'https://fmhy.net/readingpiracy',        desc: 'Ebooks, audiobooks, comics, manga, light novels, and PDF archives.' },
  { id: 'downloading', group: 'Wiki',  icon: '⬇️', name: 'Downloading',               url: 'https://fmhy.net/downloading',          desc: 'DDL sites, download managers, link unlockers, and file hosts.' },
  { id: 'torrenting',  group: 'Wiki',  icon: '🌊', name: 'Torrenting',                url: 'https://fmhy.net/torrentpiracy',        desc: 'Torrent sites, clients, trackers, and private trackers.' },
  { id: 'educational', group: 'Wiki',  icon: '🎓', name: 'Educational',               url: 'https://fmhy.net/educational',          desc: 'Courses, lectures, documentaries, textbooks, and learning platforms.' },
  { id: 'android',     group: 'Wiki',  icon: '📱', name: 'Android / iOS',             url: 'https://fmhy.net/android-iosguide',     desc: 'APKs, app stores, modded apps, iOS sideloading and jailbreaking.' },
  { id: 'linux',       group: 'Wiki',  icon: '🐧', name: 'Linux / macOS',             url: 'https://fmhy.net/linuxguide',           desc: 'Linux distros, macOS tools, shells, package managers and guides.' },
  { id: 'non-english', group: 'Wiki',  icon: '🌍', name: 'Non-English',               url: 'https://fmhy.net/non-english',          desc: 'Resources in other languages including European, Asian & more.' },
  { id: 'misc',        group: 'Wiki',  icon: '🔧', name: 'Miscellaneous',             url: 'https://fmhy.net/miscguide',            desc: "Everything that doesn't fit elsewhere — random useful tools." },
  // Tools
  { id: 'systools',    group: 'Tools', icon: '💻', name: 'System Tools',              url: 'https://fmhy.net/system-tools',         desc: 'Windows / macOS optimization, activation, drivers, and utilities.' },
  { id: 'filetools',   group: 'Tools', icon: '📁', name: 'File Tools',                url: 'https://fmhy.net/file-tools',           desc: 'File managers, archivers, converters, cloud storage, and sync.' },
  { id: 'nettools',    group: 'Tools', icon: '🌐', name: 'Internet Tools',            url: 'https://fmhy.net/internet-tools',       desc: 'Browsers, extensions, VPNs, proxies, and web utilities.' },
  { id: 'socialtools', group: 'Tools', icon: '📣', name: 'Social Media Tools',        url: 'https://fmhy.net/social-media-tools',   desc: 'Downloaders, front-ends, bots, and enhancers for social platforms.' },
  { id: 'texttools',   group: 'Tools', icon: '📝', name: 'Text Tools',                url: 'https://fmhy.net/text-tools',           desc: 'Writing aids, OCR, translators, paraphrasing, and note taking.' },
  { id: 'imgtools',    group: 'Tools', icon: '🖼️', name: 'Image Tools',               url: 'https://fmhy.net/img-tools',            desc: 'Editors, upscalers, background removers, stock photos, and AI art.' },
  { id: 'videotools',  group: 'Tools', icon: '📹', name: 'Video Tools',               url: 'https://fmhy.net/video-tools',          desc: 'Editors, converters, downloaders, recorders, and streaming tools.' },
  { id: 'audiotools',  group: 'Tools', icon: '🔊', name: 'Audio Tools',               url: 'https://fmhy.net/audio-tools',          desc: 'DAWs, editors, converters, vocal removers, and sound effects.' },
  { id: 'edutools',    group: 'Tools', icon: '🧑‍🏫', name: 'Educational Tools',        url: 'https://fmhy.net/edu-tools',            desc: 'Flashcards, study aids, homework helpers, and calculators.' },
  { id: 'devtools',    group: 'Tools', icon: '👨‍💻', name: 'Developer Tools',           url: 'https://fmhy.net/dev-tools',            desc: 'IDEs, git utilities, APIs, hosting, databases, and coding resources.' },
]

// ─────────────────────────────────────────────────────────────────────────────
// Each site: { name, url, starred?, active }
//   starred — mirrors the ⭐ rating on fmhy.net; do not change manually
//   active  — set to false to hide a site from the UI without deleting it
// After editing, re-run: VAULT_PASSWORD=urjamit node scripts/encrypt-vault.mjs
// ─────────────────────────────────────────────────────────────────────────────

export const MOVIES_SECTIONS = [
  {
    id: 'streaming',
    title: 'Streaming Sites',
    fmhyUrl: 'https://fmhy.net/videopiracy#streaming-sites',
    tip: 'Install an adblocker before visiting. Check the FMHY grading page for per-site pros/cons.',
    sites: [
      { name: 'Cineby',             url: 'https://www.cineby.sc/',              starred: true,  active: true },
      { name: 'Bitcine',            url: 'https://www.bitcine.net',                             active: true },
      { name: 'Fmovies+',          url: 'https://www.fmovies.gd',                              active: true },
      { name: 'XPrime',            url: 'https://xprime.su',                   starred: true,  active: true },
      { name: 'XPrime 2',          url: 'https://xprime.stream',               starred: true,  active: true },
      { name: 'Rive',              url: 'https://www.rivestream.app',           starred: true,  active: true },
      { name: 'Rive 2',            url: 'https://rivestream.ru',               starred: true,  active: true },
      { name: 'Rive 3',            url: 'https://rivestream.top',              starred: true,  active: true },
      { name: 'CorsFlix',          url: 'https://watch.corsflix.net',                          active: true },
      { name: 'PopcornMovies',     url: 'https://popcornmovies.org',           starred: true,  active: true },
      { name: 'BingeBox',          url: 'https://bingebox.to',                                 active: true },
      { name: 'Aether',            url: 'https://aether.mom',                  starred: true,  active: true },
      { name: 'Aether 2',          url: 'https://aether.bar',                  starred: true,  active: true },
      { name: '67Movies',          url: 'https://67movies.net',                starred: true,  active: true },
      { name: '456movie',          url: 'https://456movie.nl',                                 active: true },
      { name: 'FlickyStream',      url: 'https://flickystream.ru',             starred: true,  active: true },
      { name: 'MeowTV',            url: 'https://meowtv.ru',                                   active: true },
      { name: 'CineMora',          url: 'https://cinemora.ru',                                 active: true },
      { name: 'Cinevibe',          url: 'https://cinevibe.asia',               starred: true,  active: true },
      { name: 'Cinevibe 2',        url: 'https://cinevibe.site',                               active: true },
      { name: 'Cinevibe 3',        url: 'https://cinevibe.icu',                                active: true },
      { name: 'ShuttleTV',         url: 'https://shuttletv.su',                starred: true,  active: true },
      { name: 'Cinegram',          url: 'https://cinegram.tv/home',            starred: true,  active: true },
      { name: 'Cinetaro',          url: 'https://cinetaro.tv',                 starred: true,  active: true },
      { name: 'SpenFlix',          url: 'https://watch.spencerdevs.xyz',       starred: true,  active: true },
      { name: 'SpenFlix 2',        url: 'https://spenflix.stream',             starred: true,  active: true },
      { name: '1Shows',            url: 'https://www.1shows.org',              starred: true,  active: true },
      { name: '1Flex',             url: 'https://www.1flex.org',                               active: true },
      { name: '1Tube',             url: 'https://www.1tube.org',                               active: true },
      { name: 'Cinema.BZ',         url: 'https://cinema.bz',                                   active: true },
      { name: 'Movish',            url: 'https://movish.net',                                  active: true },
      { name: 'WatchFlix',         url: 'https://watchflix.to',                                active: true },
      { name: 'FilmCave',          url: 'https://filmcave.ru',                                 active: true },
      { name: 'Flixway',           url: 'https://flixway.pro',                                 active: true },
      { name: 'Smashystream',      url: 'https://flix.smashystream.xyz',                       active: true },
      { name: 'TVids',             url: 'https://www.tvids.to',                                active: true },
      { name: 'AZMovies',          url: 'https://azmovies.to',                                 active: true },
      { name: 'BFLIX',             url: 'https://bflix.sh',                                    active: true },
      { name: 'StreamM4u',         url: 'https://streamm4u.com.co',                            active: true },
      { name: 'M4uHD',             url: 'https://m4uhd.vip',                                   active: true },
      { name: 'Levidia',           url: 'https://www.levidia.ch',                              active: true },
      { name: 'Supernova',         url: 'https://supernova.to',                                active: true },
      { name: 'Goojara',           url: 'https://ww1.goojara.to',                              active: true },
      { name: 'PrimeWire',         url: 'https://www.primewire.mov',                           active: true },
      { name: 'ProjectFreeTV',     url: 'https://projectfreetv.sx',                            active: true },
      { name: 'Downloads-Anymovies', url: 'https://www.downloads-anymovies.co',               active: true },
    ],
  },
  {
    id: 'single-server',
    title: 'Single Server',
    fmhyUrl: 'https://fmhy.net/videopiracy#single-server',
    tip: 'Generally better speed, consistency, and fewer mislabeled titles than multi-server sites.',
    sites: [
      { name: 'NEPU',              url: 'https://nepu.to',              starred: true,  active: true },
      { name: 'EE3',               url: 'https://ee3.me',               starred: true,  active: true },
      { name: 'RIPS',              url: 'https://rips.cc',                              active: true },
      { name: 'MovieBox',          url: 'https://themoviebox.org',                      active: true },
      { name: 'CinemaCity',        url: 'https://cinemacity.cc',                        active: true },
      { name: 'RidoMovies',        url: 'https://ridomovies.tv',                        active: true },
      { name: 'OnionPlay',         url: 'https://onionplay.io',                         active: true },
      { name: 'ShowBox',           url: 'https://www.showbox.media',                    active: true },
      { name: 'UniqueStream',      url: 'https://uniquestream.net',                     active: true },
      { name: 'FshareTV',          url: 'https://fsharetv.co',                          active: true },
      { name: 'YesMovie',          url: 'https://ww1.yesmovies.ag',                     active: true },
      { name: 'HollyMovieHD',      url: 'https://hollymoviehd.cc',                      active: true },
      { name: 'HollyMovieHD 2',    url: 'https://movieboxonline.net',                   active: true },
      { name: 'HollyMovieHD 3',    url: 'https://123movie.app',                         active: true },
      { name: 'HollyMovieHD 4',    url: 'https://netnaija.film',                        active: true },
      { name: 'HollyMovieHD 5',    url: 'https://moviebox.pk',                          active: true },
      { name: 'HollyMovieHD 6',    url: 'https://moviebox.ph',                          active: true },
      { name: 'HollyMovieHD 7',    url: 'https://movieboxapp.in',                       active: true },
      { name: 'LookMovie',         url: 'https://lookmovie2.to',                        active: true },
      { name: 'LookMovie 2',       url: 'https://lookmovie2.la',                        active: true },
      { name: 'PlayIMDb',          url: 'https://www.playimdb.com',                     active: true },
      { name: 'SubSL',             url: 'https://subsl.top',                            active: true },
    ],
  },
  {
    id: 'aggregators',
    title: 'Stream Aggregators',
    fmhyUrl: 'https://fmhy.net/videopiracy#stream-aggregators',
    tip: 'Auto-test multiple streams one-by-one without manual switching.',
    sites: [
      { name: 'Flixer',       url: 'https://flixer.su',              starred: true,  active: true },
      { name: 'Hexa',         url: 'https://hexa.su',                                active: true },
      { name: 'Willow',       url: 'https://willowmovies.com',       starred: true,  active: true },
      { name: 'Cinezo',       url: 'https://www.cinezo.net',         starred: true,  active: true },
      { name: 'Flikhub',      url: 'https://www.flikhub.net',                        active: true },
      { name: 'CineBolt',     url: 'https://cinebolt.net',           starred: true,  active: true },
      { name: 'FilmyTime',    url: 'https://www.filmytime.site',     starred: true,  active: true },
      { name: 'CinemaOS',     url: 'https://cinemaos.live',          starred: true,  active: true },
      { name: 'NoirX',        url: 'https://noirx.me',                               active: true },
      { name: 'LordFlix',     url: 'https://lordflix.org',           starred: true,  active: true },
      { name: 'Primeshows',   url: 'https://www.primeshows.uk',      starred: true,  active: true },
      { name: 'NetShows',     url: 'https://netshows.xyz',                           active: true },
      { name: 'Vyla',         url: 'https://vyla.pages.dev',         starred: true,  active: true },
      { name: 'bCine',        url: 'https://bcine.app',              starred: true,  active: true },
      { name: '1Embed',       url: 'https://1embed.cc',                              active: true },
      { name: 'Poprink',      url: 'https://www.popr.ink',           starred: true,  active: true },
      { name: 'Filmex',       url: 'https://filmex.to',              starred: true,  active: true },
      { name: 'dulo.tv',      url: 'https://dulo.tv',                starred: true,  active: true },
      { name: 'Anixtv',       url: 'https://anixtv.us.cc',                           active: true },
      { name: 'P-Stream',     url: 'https://pstream.net',                            active: true },
      { name: 'ZetMoon',      url: 'https://zetmoon.live',                           active: true },
      { name: 'TouStream',    url: 'https://toustream.xyz',                          active: true },
      { name: 'IceFY',        url: 'https://icefy.top',                              active: true },
      { name: 'HydraHD',      url: 'https://hydrahd.com',                            active: true },
      { name: 'Stigstream',   url: 'https://stigstream.ru',                          active: true },
      { name: 'FilmU',        url: 'https://tv.filmu.in',                            active: true },
      { name: 'Vidbox',       url: 'https://vidbox.cc',                              active: true },
      { name: 'AuroraScreen', url: 'https://www.aurorascreen.org',                   active: true },
      { name: 'ZXCSTREAM',    url: 'https://zxcprime.icu',                           active: true },
      { name: 'Netplay',      url: 'https://netplayz.live',                          active: true },
      { name: 'Cinelove',     url: 'https://cinelove.live',                          active: true },
      { name: 'Youflex',      url: 'https://youflex.live',                           active: true },
      { name: 'StreamWatch',  url: 'https://streamwatch.online',                     active: true },
      { name: 'Mapple.tv',    url: 'https://mappl.tv',                               active: true },
      { name: '1PrimeShows',  url: 'https://1primeshow.online',                      active: true },
      { name: 'Auto Embed',   url: 'https://autoembed.app',                          active: true },
      { name: 'GaiaFlix',     url: 'https://gaiaflix.live',                          active: true },
      { name: 'PlayTorrio',   url: 'https://playtorrio.xyz',                         active: true },
      { name: 'mov-cli',      url: 'https://mov-cli.github.io',                      active: true },
    ],
  },
  {
    id: 'embed-frontends',
    title: 'Embed Frontends',
    fmhyUrl: 'https://fmhy.net/videopiracy#embed-frontends',
    tip: 'Frontend wrappers that let you select from multiple embed sources manually.',
    sites: [
      { name: 'Flicker',      url: 'https://flickermini.pages.dev',  starred: true,  active: true },
      { name: 'VoidFlix',     url: 'https://flixzy.pages.dev',       starred: true,  active: true },
      { name: 'Redflix',      url: 'https://redflix.co',                             active: true },
      { name: 'CineHub',      url: 'https://cinehub.one',                            active: true },
      { name: 'CineVibe',     url: 'https://cinevibe.to',                            active: true },
      { name: 'VibeMax',      url: 'https://vibemax.to',                             active: true },
      { name: 'MovieBite',    url: 'https://moviebite.cc',                           active: true },
      { name: 'LunaStream',   url: 'https://lunastream.fun',                         active: true },
      { name: 'Flixvo',       url: 'https://flixvo.live',                            active: true },
      { name: 'BoredFlix',    url: 'https://www.boredflix.tv',                       active: true },
      { name: 'TeleV',        url: 'https://stream.telev.tv',                        active: true },
      { name: '321Movies',    url: 'https://321movies.xyz',                          active: true },
      { name: 'AlienFlix',    url: 'https://alienflix.net',                          active: true },
      { name: 'HexaWatch',    url: 'https://hexawatch.cc',                           active: true },
      { name: 'NunFlix',      url: 'https://nunflix.li',                             active: true },
      { name: 'ONOFLIX',      url: 'https://onoflix.ru',                             active: true },
      { name: 'GGFlix',       url: 'https://ggflix.live',                            active: true },
      { name: 'Bingeflix',    url: 'https://bingeflix.tv',                           active: true },
      { name: '7REELS',       url: 'https://7reels.cc',                              active: true },
      { name: 'Streamr',      url: 'https://streamr.pages.dev',                      active: true },
      { name: 'Cubeflix',     url: 'https://cubeflix.org',                           active: true },
      { name: 'Way2Movies',   url: 'https://way2movies.live',                        active: true },
      { name: 'CinebyTV',     url: 'https://cinebytv.com',                           active: true },
      { name: 'zmov',         url: 'https://plexmovies.online',                      active: true },
      { name: 'KaitoVault',   url: 'https://www.kaitovault.com',                     active: true },
      { name: 'Yampi',        url: 'https://yampi.live',                             active: true },
      { name: 'M-Zone',       url: 'https://www.m-zone.org',                         active: true },
      { name: 'FluxTV',       url: 'https://fluxtv.qzz.io',                          active: true },
      { name: 'StreameX',     url: 'https://streamex.sh',                            active: true },
      { name: 'Zerostream',   url: 'https://zerostream.alwaysdata.net',              active: true },
      { name: 'Snowstream',   url: 'https://snowstream.vercel.app',                  active: true },
      { name: 'ViewfFix',     url: 'https://flixwatch.online',                       active: true },
      { name: 'StreamGoblin', url: 'https://streamgoblin.com',                       active: true },
      { name: 'Warflix',      url: 'https://warflix.nl',                             active: true },
      { name: 'Heartive',     url: 'https://heartivetv.pages.dev',                   active: true },
      { name: 'Ask4Movies',   url: 'https://ask4movie.app',                          active: true },
      { name: 'CineGo',       url: 'https://cinego.co',                              active: true },
      { name: 'Moviepire',    url: 'https://moviepire.org',                          active: true },
    ],
  },
  {
    id: 'free-ads',
    title: 'Free with Ads',
    fmhyUrl: 'https://fmhy.net/videopiracy#free-w-ads',
    tip: 'Fully legal, ad-supported streaming — use an adblocker for a better experience.',
    sites: [
      { name: 'Tubi',             url: 'https://tubitv.com',                                          starred: true,  active: true },
      { name: 'Plex',             url: 'https://watch.plex.tv',                                       starred: true,  active: true },
      { name: 'Pluto',            url: 'https://pluto.tv',                                            starred: true,  active: true },
      { name: 'PopcornFlix',      url: 'https://popcornflix.com',                                                     active: true },
      { name: 'Prime Video Free', url: 'https://www.amazon.com/gp/video/storefront/?ie=UTF8&contentId=freetv',        active: true },
      { name: 'Roku',             url: 'https://therokuchannel.roku.com',                                             active: true },
      { name: 'DarkRoom',         url: 'https://www.darkroom.film',                                                   active: true },
      { name: 'Fawesome',         url: 'https://fawesome.tv',                                                         active: true },
      { name: 'Sling',            url: 'https://watch.sling.com',                                                     active: true },
      { name: 'Mometu',           url: 'https://watch.mometu.com',                                                    active: true },
      { name: 'Fandango',         url: 'https://athome.fandango.com/content/browse/free',                             active: true },
      { name: 'Shout! TV',        url: 'https://shout-tv.com',                                                        active: true },
      { name: 'Kanopy',           url: 'https://www.kanopy.com',                                                      active: true },
      { name: 'hoopla',           url: 'https://www.hoopladigital.com',                                               active: true },
      { name: 'Found TV',         url: 'https://watch.foundtv.com',                                                   active: true },
      { name: '7+',               url: 'https://7plus.com.au',                                                        active: true },
      { name: 'Playary',          url: 'https://www.playary.com',                                                     active: true },
      { name: 'Filmzie',          url: 'https://filmzie.com',                                                         active: true },
      { name: 'ARTE',             url: 'https://www.arte.tv',                                                         active: true },
      { name: 'BBC iPlayer',      url: 'https://www.bbc.co.uk/iplayer',                                               active: true },
      { name: 'FlixHouse',        url: 'https://flixhouse.com',                                                       active: true },
    ],
  },
  {
    id: 'video-streaming',
    title: 'Video Streaming',
    fmhyUrl: 'https://fmhy.net/videopiracy#video-streaming',
    tip: 'Good for finding classic, obscure, and short films.',
    sites: [
      { name: 'VK',          url: 'https://vkvideo.ru',          starred: true,  active: true },
      { name: 'YouTube',     url: 'https://www.youtube.com',     starred: true,  active: true },
      { name: 'Dailymotion', url: 'https://www.dailymotion.com', starred: true,  active: true },
      { name: 'BiliBili',    url: 'https://www.bilibili.com',    starred: true,  active: true },
      { name: 'BiliBili.tv', url: 'https://www.bilibili.tv',     starred: true,  active: true },
      { name: 'Niconico',    url: 'https://www.nicovideo.jp',    starred: true,  active: true },
      { name: 'PeerTube',    url: 'https://joinpeertube.org',                    active: true },
      { name: 'Vimeo',       url: 'https://vimeo.com',                           active: true },
      { name: 'rutube',      url: 'https://rutube.ru',                           active: true },
      { name: 'Videa',       url: 'https://videa.hu',                            active: true },
      { name: 'BitView',     url: 'https://www.bitview.net',                     active: true },
      { name: 'Tape',        url: 'https://tape.xyz',                            active: true },
      { name: 'Naver',       url: 'https://tv.naver.com',                        active: true },
      { name: 'ultimedia',   url: 'https://www.ultimedia.com',                   active: true },
      { name: 'odysee',      url: 'https://odysee.com',                          active: true },
      { name: 'Rumble',      url: 'https://rumble.com',                          active: true },
      { name: 'DeafVideo',   url: 'https://www.deafvideo.tv',                    active: true },
    ],
  },
  {
    id: 'specialty',
    title: 'Specialty Streaming',
    fmhyUrl: 'https://fmhy.net/videopiracy#specialty-streaming',
    tip: 'Niche content — documentaries, courses, rare films, and experimental shorts.',
    sites: [
      { name: 'RareFilmm',             url: 'https://rarefilmm.com',                   starred: true,  active: true },
      { name: 'JP-Films',              url: 'https://jp-films.com',                    starred: true,  active: true },
      { name: 'Tokuzilla',             url: 'https://tokuzilla.net',                   starred: true,  active: true },
      { name: 'GizmoPlex',             url: 'https://www.gizmoplex.com/mst3k',         starred: true,  active: true },
      { name: 'Ubu',                   url: 'https://ubu.com/film',                    starred: true,  active: true },
      { name: 'LIMA',                  url: 'https://www.li-ma.nl',                                    active: true },
      { name: 'LightCone',             url: 'https://lightcone.org/en',                                active: true },
      { name: 'Viddsee',               url: 'https://www.viddsee.com',                                 active: true },
      { name: 'Shortverse',            url: 'https://www.shortverse.com/explore',                      active: true },
      { name: 'Short of the Week',     url: 'https://www.shortoftheweek.com',                          active: true },
      { name: 'Argo',                  url: 'https://web.watchargo.com',                               active: true },
      { name: '0xDB',                  url: 'https://0xdb.org',                                        active: true },
      { name: 'HomeMovies101',         url: 'https://www.homemovies100.it/en',                         active: true },
      { name: 'Prelinger Archives',    url: 'https://archive.org/details/prelinger',                   active: true },
      { name: 'GlobalShakespeares',    url: 'https://globalshakespeares.mit.edu',                      active: true },
      { name: 'TVARK',                 url: 'https://tvark.org',                                       active: true },
      { name: 'Daily Commercials',     url: 'https://dailycommercials.com',                            active: true },
      { name: 'MovieCommentaries',     url: 'https://www.youtube.com/@moviecommentaries',              active: true },
      { name: 'SpecialFeatureArchive', url: 'https://youtube.com/@specialfeaturesarchive',             active: true },
    ],
  },
  {
    id: 'anime',
    title: 'Anime Streaming',
    fmhyUrl: 'https://fmhy.net/videopiracy#anime-streaming',
    tip: 'Check Wotaku or The Index for a full anime site index with ratings.',
    sites: [
      { name: 'Miruro',          url: 'https://www.miruro.com',              starred: true,  active: true },
      { name: 'All Manga',       url: 'https://allmanga.to',                 starred: true,  active: true },
      { name: 'animepahe',       url: 'https://animepahe.pw',               starred: true,  active: true },
      { name: 'KickAssAnime',    url: 'https://kaa.to',                     starred: true,  active: true },
      { name: 'Animetsu',        url: 'https://animetsu.net',               starred: true,  active: true },
      { name: 'AnimeX',          url: 'https://animex.one',                 starred: true,  active: true },
      { name: 'Anidap',          url: 'https://anidap.se',                  starred: true,  active: true },
      { name: 'Kuroiru',         url: 'https://kuroiru.co',                 starred: true,  active: true },
      { name: 'Seanime',         url: 'https://seanime.app',                starred: true,  active: true },
      { name: 'AnymeX',          url: 'https://anymex.vercel.app',                          active: true },
      { name: 'Anikin',          url: 'https://github.com/jerry08/Anikin',                  active: true },
      { name: 'Unyo',            url: 'https://github.com/K3vinb5/Unyo',                    active: true },
      { name: 'Miru',            url: 'https://miru.js.org/en',                             active: true },
      { name: 'Yenime',          url: 'https://yenime.net',                                 active: true },
      { name: 'Anify',           url: 'https://anify.to',                                   active: true },
      { name: '123anime',        url: 'https://123animes.ru',                               active: true },
      { name: '1Anime',          url: 'https://1ani.me',                                    active: true },
      { name: 'Re:ANIME',        url: 'https://reanime.to',                                 active: true },
      { name: 'AniDoor',         url: 'https://anidoor.me',                                 active: true },
      { name: 'Aniverse',        url: 'https://aniverse.watch',                             active: true },
      { name: 'Anistream',       url: 'https://anistream.one',                              active: true },
      { name: 'Enma',            url: 'https://www.enma.lol',                               active: true },
      { name: 'JustAnime',       url: 'https://justanime.to',                               active: true },
      { name: 'AniKuro',         url: 'https://anikuro.to',                                 active: true },
      { name: 'Anime Silo',      url: 'https://animesilo.cc',                               active: true },
      { name: 'Kawaii Anime',    url: 'https://kawaii-anime.com',                           active: true },
      { name: 'AnimeNoSub',      url: 'https://animenosub.to',                              active: true },
      { name: 'Kiroku',          url: 'https://kiroku.my',                                  active: true },
      { name: 'Anime Nexus',     url: 'https://anime.nexus',                                active: true },
      { name: 'AnimeHub',        url: 'https://animehub.ac',                                active: true },
      { name: 'AniZone',         url: 'https://anizone.to',                                 active: true },
      { name: 'AniHQ',           url: 'https://anihq.to',                                   active: true },
      { name: 'GojoStream',      url: 'https://www.modsyndicate.com',                       active: true },
      { name: 'Animelok',        url: 'https://animelok.xyz',                               active: true },
      { name: 'Anisuge',         url: 'https://animesuge.cz',                               active: true },
      { name: 'Lunar',           url: 'https://lunaranime.ru',                              active: true },
      { name: 'Anoboye',         url: 'https://anoboye.com',                                active: true },
      { name: 'Senshi',          url: 'https://senshi.live',                                active: true },
      { name: 'Anime Realms',    url: 'https://www.animerealms.org',                        active: true },
      { name: 'AnimeParadise',   url: 'https://www.animeparadise.moe',                      active: true },
      { name: 'KissAnime',       url: 'https://kissanime.com.ru',                           active: true },
      { name: 'AnimeOnsen',      url: 'https://animeonsen.xyz',                             active: true },
      { name: 'AnimeStream',     url: 'https://anime.uniquestream.net',                     active: true },
      { name: 'FireAnime',       url: 'https://fireani.me',                                 active: true },
      { name: 'PirateXplay',     url: 'https://piratexplay.cc/home',                        active: true },
      { name: 'AnimeXin',        url: 'https://animexin.dev',                               active: true },
      { name: 'Lucifer Donghua', url: 'https://luciferdonghua.in',                          active: true },
      { name: 'LMANIME',         url: 'https://lmanime.com',                                active: true },
      { name: 'CKSub',           url: 'https://cksub.org',                                  active: true },
      { name: 'MyAnime',         url: 'https://myanime.live',                               active: true },
      { name: 'AnimeKhor',       url: 'https://animekhor.org',                              active: true },
      { name: 'Crimson Subs',    url: 'https://crimsonfansubs.com',                         active: true },
      { name: 'Kara.moe',        url: 'https://kara.moe',                                   active: true },
      { name: 'AnimeThemes',     url: 'https://animethemes.moe',                            active: true },
      { name: 'Miu',             url: 'https://discord.gg/pwkuanXBJh',                      active: true },
    ],
  },
  {
    id: 'cartoons',
    title: 'Cartoon Streaming',
    fmhyUrl: 'https://fmhy.net/videopiracy#cartoon-streaming',
    tip: 'Western animation — classic and modern cartoons.',
    sites: [
      { name: 'WCO',                             url: 'https://www.wco.tv',                                          starred: true,  active: true },
      { name: 'KimCartoon',                      url: 'https://kimcartoon.si',                                       starred: true,  active: true },
      { name: 'KissCartoon',                     url: 'https://kisscartoon.nz',                                                      active: true },
      { name: 'HiCartoons',                      url: 'https://hicartoon.to',                                                        active: true },
      { name: 'PirateXplay',                     url: 'https://piratexplay.cc/home',                                                 active: true },
      { name: 'FunnierMoments',                  url: 'https://www.funniermoments.net',                                              active: true },
      { name: 'Kartoons',                        url: 'https://kartoons.me',                                                         active: true },
      { name: 'B98',                             url: 'https://www.b98.tv/home',                                                     active: true },
      { name: 'ToonTales',                       url: 'https://www.toontales.net',                                                   active: true },
      { name: 'SuperCartoons',                   url: 'https://www.supercartoons.net',                                               active: true },
      { name: 'Japanese Animated Film Classics', url: 'https://animation.filmarchives.jp/index.html',                                active: true },
      { name: 'Eddvault',                        url: 'https://eddvault.notion.site/Eddvault-3b7700da57bd4d429b927c1733ccb772',     active: true },
    ],
  },
  {
    id: 'tv',
    title: 'TV Streaming',
    fmhyUrl: 'https://fmhy.net/videopiracy#tv-streaming',
    tip: 'Sites focused exclusively on TV content.',
    sites: [
      { name: 'Best Series',     url: 'https://bstsrs.in',                   starred: true,  active: true },
      { name: 'NOXX',            url: 'https://noxx.to',                     starred: true,  active: true },
      { name: 'AZ Series',       url: 'https://azseries.org',                                active: true },
      { name: 'HISTORY',         url: 'https://play.history.com',                            active: true },
      { name: 'Adult Swim',      url: 'https://www.adultswim.com',                           active: true },
      { name: 'DisneyNOW',       url: 'https://disneynow.com',                               active: true },
      { name: 'SFBTV',           url: 'https://diva.sfsu.edu/collections/sfbatv',            active: true },
      { name: 'HDclump',         url: 'https://hdclump.com',                                 active: true },
      { name: 'BrokenSilenze',   url: 'https://www.brokensilenze.net',                       active: true },
      { name: 'r/Panelshow',     url: 'https://www.reddit.com/r/panelshow',                  active: true },
      { name: 'Taskmaster',      url: 'https://rentry.co/bbbr4cfr',                          active: true },
      { name: 'The Silent Library', url: 'https://thesilentlibrary.com',                     active: true },
      { name: 'MyRM',            url: 'https://myrunningman.com',                            active: true },
      { name: 'TWC Classics',    url: 'https://twcclassics.com',                             active: true },
    ],
  },
  {
    id: 'drama',
    title: 'Drama Streaming',
    fmhyUrl: 'https://fmhy.net/videopiracy#drama-streaming',
    tip: 'Asian dramas — Korean, Chinese, Japanese, and more.',
    sites: [
      { name: 'GoPlay',          url: 'https://goplay.su',               starred: true,  active: true },
      { name: 'Dramacool',       url: 'https://wv.dramacool.com.tr',     starred: true,  active: true },
      { name: 'Einthusan',       url: 'https://einthusan.tv/intro',                      active: true },
      { name: 'KissAsian',       url: 'https://ww14.kissasian.com.lv',                  active: true },
      { name: 'KissKH',          url: 'https://kisskh.ovh',                              active: true },
      { name: 'DramaNice',       url: 'https://dramanice.boo',                           active: true },
      { name: 'Dramahood',       url: 'https://dramahood.mom',                           active: true },
      { name: 'Asiaflix',        url: 'https://asiaflix.net',                            active: true },
      { name: 'KissAsian.video', url: 'https://kissasian.video',                         active: true },
      { name: 'AsianCrush',      url: 'https://www.asiancrush.com',                      active: true },
      { name: 'AsianSubs',       url: 'https://asiansubs.com',                           active: true },
      { name: 'OnDemandChina',   url: 'https://www.ondemandchina.com',                   active: true },
    ],
  },
  {
    id: 'classics',
    title: 'Classics / Public Domain',
    fmhyUrl: 'https://fmhy.net/videopiracy#classics-public-domain',
    tip: 'Legally free films — public domain, silent era, and restored classics.',
    sites: [
      { name: 'Internet Archive',                   url: 'https://archive.org/details/moviesandfilms', starred: true,  active: true },
      { name: 'WikiFlix',                           url: 'https://wikiflix.toolforge.org',              starred: true,  active: true },
      { name: 'Classic Cinema Online',              url: 'https://classiccinemaonline.com',                             active: true },
      { name: 'The Classic Movies',                 url: 'https://www.the-classic-movies.com',                         active: true },
      { name: 'RetroFlix',                          url: 'https://retroflix.org',                                       active: true },
      { name: 'moonflix',                           url: 'https://moonflix.com',                                        active: true },
      { name: 'RetroStrange',                       url: 'https://retrostrange.com',                                    active: true },
      { name: 'NASA+',                              url: 'https://plus.nasa.gov',                                       active: true },
      { name: 'FilmsByTheYear',                     url: 'https://www.youtube.com/@FilmsbytheYear/playlists',           active: true },
      { name: 'Wu Tang Collection',                 url: 'https://www.thewutangcollection.com',                         active: true },
      { name: 'Silent Hall of Fame',                url: 'https://silent-hall-of-fame.org',                             active: true },
      { name: 'Danish Silent Film',                 url: 'https://www.stumfilm.dk/en/stumfilm',                         active: true },
      { name: 'FootageFarm',                        url: 'https://footagefarm.com',                                     active: true },
      { name: 'Public Domain Movies',               url: 'https://publicdomainmovie.net',                               active: true },
      { name: 'Cinetimes',                          url: 'https://cinetimes.org/en',                                    active: true },
      { name: 'commons.wikimedia',                  url: 'https://commons.wikimedia.org/wiki/Category:Videos',         active: true },
      { name: 'Historic Films',                     url: 'https://www.historicfilms.com',                               active: true },
      { name: 'National Film Preservation Foundation', url: 'https://www.filmpreservation.org',                         active: true },
    ],
  },
  {
    id: 'film-archives',
    title: 'Film Archives',
    fmhyUrl: 'https://fmhy.net/videopiracy#film-archives',
    tip: 'Official national and regional film archives from around the world.',
    sites: [
      { name: 'The Library of Congress',        url: 'https://www.loc.gov/film-and-videos',                                               starred: true,  active: true },
      { name: 'USNationalArchives',             url: 'https://www.youtube.com/@USNationalArchives',                                        starred: true,  active: true },
      { name: 'HuntleyArchives',                url: 'https://www.huntleyarchives.com',                                                                    active: true },
      { name: 'European Film Gateway',          url: 'https://www.europeanfilmgateway.eu',                                                                 active: true },
      { name: 'Eastern European Movies',        url: 'https://easterneuropeanmovies.com',                                                                  active: true },
      { name: 'BFIPlayer',                      url: 'https://player.bfi.org.uk/free',                                                                     active: true },
      { name: 'British Pathé',                  url: 'https://www.britishpathe.com',                                                                       active: true },
      { name: 'ColonialFilm',                   url: 'http://www.colonialfilm.org.uk',                                                                      active: true },
      { name: 'Imperial War Museums',           url: 'https://www.iwm.org.uk',                                                                             active: true },
      { name: 'Atom Central',                   url: 'https://www.atomcentral.com',                                                                        active: true },
      { name: 'yfanefa',                        url: 'https://www.yfanefa.com',                                                                            active: true },
      { name: 'nfb.ca',                         url: 'https://www.nfb.ca',                                                                                 active: true },
      { name: 'IndianCine',                     url: 'https://indiancine.ma',                                                                              active: true },
      { name: 'National Film Archive of Japan', url: 'https://meiji.filmarchives.jp',                                                                      active: true },
      { name: 'CCLM',                           url: 'https://www.cclm.cl/cineteca-online',                                                                active: true },
      { name: 'NFSA',                           url: 'https://www.nfsa.gov.au',                                                                            active: true },
      { name: 'NGA Taonga',                     url: 'https://www.ngataonga.org.nz/search-use-collection/search',                                          active: true },
      { name: 'NZOnScreen',                     url: 'https://www.nzonscreen.com',                                                                         active: true },
      { name: 'NLS',                            url: 'https://www.nls.uk',                                                                                 active: true },
      { name: 'Northern Ireland Screen',        url: 'https://digitalfilmarchive.net',                                                                     active: true },
      { name: 'IFI Archive',                    url: 'https://ifiarchiveplayer.ie',                                                                        active: true },
      { name: 'Cinematheque',                   url: 'https://www.cinematheque.fr/henri/english',                                                          active: true },
      { name: 'Stiftung imai',                  url: 'https://stiftung-imai.de',                                                                           active: true },
      { name: 'Film Portal',                    url: 'https://www.filmportal.de/en/videos',                                                                active: true },
      { name: 'RussianFilmHub',                 url: 'https://russianfilmhub.com',                                                                         active: true },
      { name: 'Cinemata',                       url: 'https://cinemata.org',                                                                               active: true },
      { name: 'Austrian Film Museum',           url: 'https://www.filmmuseum.at/jart/prj3/filmmuseum/main.jart?rel=en',                                    active: true },
      { name: '35mm',                           url: 'https://35mm.online/en',                                                                             active: true },
      { name: 'TexasArchive',                   url: 'https://texasarchive.org',                                                                           active: true },
      { name: 'Chicago Film Archives',          url: 'https://www.chicagofilmarchives.org',                                                                active: true },
      { name: 'The Travel Film Archive',        url: 'https://travelfilmarchive.com',                                                                      active: true },
      { name: 'DVIDS',                          url: 'https://www.dvidshub.net',                                                                           active: true },
    ],
  },
  {
    id: 'live-tv',
    title: 'Live TV',
    fmhyUrl: 'https://fmhy.net/videopiracy#live-tv',
    tip: 'Use an adblocker. Try a VPN if sites are blocked in your country.',
    sites: [
      { name: 'NTV',            url: 'http://ntv.cx',                                                                    starred: true,  active: true },
      { name: 'StreamSports99', url: 'https://streamsports99.su/live-tv',                                                 starred: true,  active: true },
      { name: 'Famelack',       url: 'https://famelack.com',                                                             starred: true,  active: true },
      { name: 'EasyWebTV',      url: 'https://zhangboheng.github.io/Easy-Web-TV-M3u8/routes/countries.html',             starred: true,  active: true },
      { name: 'IPTV Web',       url: 'https://iptv-web.app',                                                                             active: true },
      { name: 'DaddyLive TV',   url: 'https://dlhd.pk/24-7-channels.php',                                               starred: true,  active: true },
      { name: 'TVPass',         url: 'https://tvpass.org',                                                               starred: true,  active: true },
      { name: 'SportsBite TV',  url: 'https://livetv.moviebite.cc/channels',                                            starred: true,  active: true },
      { name: 'TitanTV',        url: 'https://titantv.com',                                                                              active: true },
      { name: 'TV Freedom',     url: 'https://tvfreedom.surge.sh',                                                                       active: true },
      { name: 'Xumo Play',      url: 'https://play.xumo.com/networks',                                                                   active: true },
      { name: 'Pluto',          url: 'https://pluto.tv',                                                                                 active: true },
      { name: 'huhu.to',        url: 'https://huhu.to',                                                                                  active: true },
      { name: 'vavoo.to',       url: 'https://vavoo.to',                                                                                 active: true },
      { name: 'kool.to',        url: 'https://kool.to',                                                                                  active: true },
      { name: 'oha.to',         url: 'https://oha.to',                                                                                   active: true },
      { name: 'LiveHDTV',       url: 'https://www.livehdtv.com',                                                                         active: true },
      { name: 'CineBolt TV',    url: 'https://cinebolt.net/live',                                                                        active: true },
      { name: 'Movish TV',      url: 'https://movish.net/live-broadcasts',                                                               active: true },
      { name: 'Globe TV',       url: 'https://globetv.app',                                                                              active: true },
      { name: 'uFreeTV',        url: 'https://ufreetv.com',                                                                              active: true },
      { name: 'TV247US',        url: 'https://tv247us.vip',                                                                              active: true },
      { name: 'SportOnTV',      url: 'https://sportontv.biz',                                                                            active: true },
      { name: 'SportDB TV',     url: 'https://hoofoot.ru/tv',                                                                            active: true },
      { name: 'CXtv',           url: 'https://www.cxtvlive.com',                                                                         active: true },
      { name: 'WatchTVs',       url: 'https://watchtvs.live',                                                                            active: true },
      { name: 'Cubik TV',       url: 'https://cubiktv.com',                                                                              active: true },
      { name: 'Rive Live',      url: 'https://rivestream.org/iptv',                                                                      active: true },
      { name: 'iShowMovies',    url: 'https://ishowmovies.org/live',                                                                     active: true },
      { name: 'FreeInterTV',    url: 'http://www.freeintertv.com',                                                                       active: true },
      { name: 'Global Free TV',  url: 'https://www.globalfreetv.com',                                                                    active: true },
      { name: 'SquidTV',        url: 'https://www.squidtv.net',                                                                          active: true },
      { name: 's7-tv',          url: 'https://s7-tv.blogspot.com/p/t.html',                                                              active: true },
      { name: 'DistroTV',       url: 'https://distro.tv',                                                                                active: true },
      { name: 'Puffer',         url: 'https://puffer.stanford.edu',                                                                      active: true },
      { name: 'cytube',         url: 'https://cytu.be',                                                                                  active: true },
      { name: 'VaughnLive',     url: 'https://vaughn.live/browse/misc',                                                                  active: true },
      { name: 'YTCH',           url: 'https://ytch.tv',                                                                                  active: true },
      { name: 'Channel Surfer',  url: 'https://channelsurfer.tv',                                                                        active: true },
      { name: 'FreeTVz',        url: 'https://freetvz.com',                                                                              active: true },
      { name: 'TV.Jest',        url: 'https://tv.jest.one',                                                                              active: true },
      { name: 'Split TV',       url: 'https://split-tv.co.il',                                                                           active: true },
      { name: 'WorldNews24',    url: 'https://worldnews24.tv',                                                                           active: true },
      { name: 'SHOWROOM',       url: 'https://showroom-live.com',                                                                        active: true },
      { name: 'Koryo TV',       url: 'https://koryo.tv',                                                                                 active: true },
      { name: 'KCNA',           url: 'https://kcnawatch.us/korea-central-tv-livestream',                                                 active: true },
    ],
  },
  {
    id: 'live-sports',
    title: 'Live Sports',
    fmhyUrl: 'https://fmhy.net/videopiracy#live-sports',
    tip: 'Use an adblocker. Try a VPN if sites are blocked.',
    sites: [
      { name: 'Streamed',        url: 'https://streamed.pk',              starred: true,  active: true },
      { name: 'SportyHunter',    url: 'https://sportyhunter.space',       starred: true,  active: true },
      { name: 'Watch Footy',     url: 'https://watchfooty.st',            starred: true,  active: true },
      { name: 'BINTV',           url: 'https://bintv.net',                starred: true,  active: true },
      { name: 'WatchSports',     url: 'https://watchsports.to',           starred: true,  active: true },
      { name: 'DaddyLive',       url: 'https://dlhd.pk',                  starred: true,  active: true },
      { name: 'SportsBite',      url: 'https://livetv.moviebite.cc',      starred: true,  active: true },
      { name: 'LiveTV',          url: 'https://livetv.sx/enx',            starred: true,  active: true },
      { name: 'TimStreams',       url: 'https://timstreams.net',                           active: true },
      { name: 'SportDB',         url: 'https://hoofoot.ru',                               active: true },
      { name: 'StreamFree',      url: 'https://streamfree.app',                           active: true },
      { name: 'Sportsurge',      url: 'https://v2.sportsurge.net/home5',                  active: true },
      { name: 'TotalSportek',    url: 'https://totalsportek.tips',                        active: true },
      { name: 'DamiTV',          url: 'https://dami-tv.pro',                              active: true },
      { name: '90minutes',       url: 'https://www.90minutes.xyz',                        active: true },
      { name: 'DaddyLiveHD',     url: 'https://daddylive.org',                            active: true },
      { name: 'FootStreams',      url: 'https://footstreams.xyz',                          active: true },
      { name: 'Ask4Sports',      url: 'https://ask4sport.xyz',                            active: true },
      { name: 'FSL',             url: 'https://freestreams-live1a.pk',                    active: true },
      { name: 'Footfy',          url: 'https://footfy.net',                               active: true },
      { name: '1Ball',           url: 'https://1ball.pk',                                 active: true },
      { name: 'StreamCorner',    url: 'https://streamcorner.vu',                          active: true },
      { name: 'FoxTrend',        url: 'https://foxtrend.vip',                             active: true },
      { name: 'CricHD',          url: 'https://crichd.at',                                active: true },
      { name: 'FalconStreams',    url: 'https://falconstreams.net',                        active: true },
      { name: 'Streami',         url: 'https://streami.top',                              active: true },
      { name: 'MainPortal66',    url: 'https://mainportal66.com',                         active: true },
      { name: 'PPV.TO',          url: 'https://ppv.to',                                   active: true },
      { name: 'Vuen Link',       url: 'https://vuen.link',                                active: true },
      { name: 'FCTV33',          url: 'https://www.fctv33.lat',                           active: true },
      { name: 'MrGamingStreams', url: 'http://mrgamingstreams.org',                       active: true },
      { name: 'Sports Plus',     url: 'https://en12.sportplus.live',                      active: true },
      { name: 'VIP Box Sports',  url: 'https://www.viprow.co',                            active: true },
      { name: 'StreamEast',      url: 'https://streameast.ga',                            active: true },
      { name: '720pStream',      url: 'https://720pstream.lc',                            active: true },
      { name: 'BuffStream',      url: 'https://app.buffstream.io',                        active: true },
      { name: 'RoxieStreams',    url: 'https://roxiestreams.su',                          active: true },
      { name: 'FawaNews',        url: 'http://www.fawanews.sc',                           active: true },
      { name: 'FootFast',        url: 'https://footfast.cc',                              active: true },
      { name: 'Sports24',        url: 'https://sports24.cc',                              active: true },
      { name: 'SharkStreams',    url: 'https://sharkstreams.net',                         active: true },
      { name: 'CrackStreams.ms', url: 'https://crackstreams.ms',                          active: true },
      { name: 'NBAMonster',      url: 'https://nbamonster.com',                           active: true },
      { name: 'WebCric',         url: 'https://me.webcric.com',                           active: true },
      { name: 'OnHockey',        url: 'https://onhockey.tv',                              active: true },
      { name: 'Pitsport',        url: 'https://pitsport.live',                            active: true },
      { name: 'OvertakeFans',    url: 'https://overtakefans.com',                         active: true },
      { name: 'Aceztrims',       url: 'https://acestrlms.pages.dev',                      active: true },
      { name: 'DD12',            url: 'https://dd12streams.com',                          active: true },
      { name: 'NontonGP',        url: 'https://esp32.nontonx.com',                        active: true },
      { name: 'r/rugbystreams',  url: 'https://www.reddit.com/r/rugbystreams',            active: true },
      { name: 'Tiz-Cycling',     url: 'https://tiz-cycling.tv',                           active: true },
    ],
  },
  {
    id: 'sports-replays',
    title: 'Sports Replays',
    fmhyUrl: 'https://fmhy.net/videopiracy#sports-replays',
    tip: 'Full match replays and classic sports archives.',
    sites: [
      { name: '720pier',                url: 'https://720pier.ru',                                                                  starred: true,  active: true },
      { name: 'Basketball Video',       url: 'https://basketball-video.com',                                                        starred: true,  active: true },
      { name: 'Footballia',             url: 'https://footballia.net',                                                              starred: true,  active: true },
      { name: 'Watch-Wrestling.eu',     url: 'https://watch-wrestling.eu',                                                          starred: true,  active: true },
      { name: '1Max',                   url: 'https://1max.top',                                                                    starred: true,  active: true },
      { name: 'RealFights',             url: 'https://realfight.top',                                                                               active: true },
      { name: 'Nascar Classics',        url: 'https://classics.nascar.com',                                                        starred: true,  active: true },
      { name: 'FullRaces',              url: 'https://fullraces.com',                                                               starred: true,  active: true },
      { name: 'Classic Sports Fanatic', url: 'https://www.youtube.com/@classicsportsfanatic7183/playlists',                                         active: true },
      { name: 'NFL Video',              url: 'https://nfl-video.com',                                                                               active: true },
      { name: 'BasketballReplays',      url: 'https://basketballreplays.net',                                                                       active: true },
      { name: 'MLBLive',                url: 'https://mlblive.net',                                                                                 active: true },
      { name: 'Steves Classic Baseball',url: 'https://www.youtube.com/playlist?list=PLbbmEcFXHSnOHeJdpQr0K808cPVzP0t_B',                           active: true },
      { name: 'FootballOrigin',         url: 'https://www.footballorgin.com',                                                                       active: true },
      { name: 'FullMatchShows',         url: 'https://fullmatchshows.com',                                                                          active: true },
      { name: 'r/footballhighlights',   url: 'https://www.reddit.com/r/footballhighlights',                                                         active: true },
      { name: 'Time Soccer TV',         url: 'https://timesoccertv.com',                                                                            active: true },
      { name: 'SoccerFull',             url: 'https://soccerfull.net',                                                                              active: true },
      { name: 'HooFoot',                url: 'https://hoofoot.com',                                                                                 active: true },
      { name: 'MySoccerPulse',          url: 'https://mysoccerpulse.com',                                                                           active: true },
      { name: 'RuTracker Sports',       url: 'https://rutracker.org/forum/index.php?c=28',                                                          active: true },
      { name: 'Sport Video',            url: 'https://www.sport-video.org.ua',                                                                      active: true },
      { name: 'WatchProWrestling',      url: 'https://watchprowrestlings.live',                                                                     active: true },
      { name: 'WatchWrestling.ae',      url: 'https://watchwrestling.ae',                                                                           active: true },
      { name: 'WatchWrestling.st',      url: 'https://watchwrestling.st',                                                                           active: true },
      { name: 'PWrestling',             url: 'https://pwrestling.com',                                                                              active: true },
      { name: 'AllWrestling24',         url: 'https://allwrestling24.com',                                                                          active: true },
      { name: '123Wrestling',           url: 'https://123wrestling.com',                                                                            active: true },
      { name: 'Miselet',                url: 'https://vkvideo.ru/@miselet',                                                                         active: true },
      { name: 'AllTheBestFights',       url: 'https://www.allthebestfights.com',                                                                    active: true },
      { name: 'TNA / Impact Replays',   url: 'https://www.youtube.com/playlist?list=PLSadBNbijyoGV44wd96Fda7-GDYh9UktC',                           active: true },
      { name: 'OvertakeFans',           url: 'https://overtakefans.com',                                                                            active: true },
      { name: 'r/MotorsportsReplays',   url: 'https://www.reddit.com/r/MotorsportsReplays',                                                         active: true },
      { name: 'F1 Full Races',          url: 'https://f1fullraces.com',                                                                             active: true },
      { name: 'NontonGP',               url: 'https://esp32.nontonx.com',                                                                           active: true },
      { name: 'Rugby24',                url: 'https://rugby24.net',                                                                                 active: true },
    ],
  },
  {
    id: 'download-sites',
    title: 'Download Sites',
    fmhyUrl: 'https://fmhy.net/videopiracy#download-sites',
    tip: 'Direct download sites. Use a redirect bypasser for link shorteners.',
    sites: [
      { name: 'Scloud',             url: 'https://rentry.co/FMHYB64#sc',                             starred: true,  active: true },
      { name: 'Acer Movies',        url: 'https://rentry.co/FMHYB64#acer',                           starred: true,  active: true },
      { name: 'VegaMovies',         url: 'https://vegamovies.market',                                starred: true,  active: true },
      { name: 'Pahe',               url: 'https://pahe.ink',                                         starred: true,  active: true },
      { name: 'DDLBase',            url: 'https://ddlbase.com',                                      starred: true,  active: true },
      { name: 'XDMovies',           url: 'https://top.xdmovies.wtf',                                 starred: true,  active: true },
      { name: 'MovieParadise',      url: 'https://movieparadise.org',                                starred: true,  active: true },
      { name: 'Drama Day',          url: 'https://dramaday.me',                                      starred: true,  active: true },
      { name: 'MKVDrama',           url: 'https://mkvdrama.net',                                     starred: true,  active: true },
      { name: 'PlayTorrio',         url: 'https://playtorrio.xyz',                                                   active: true },
      { name: 'GoatAPI Downloader', url: 'https://goatapi.imreallydagoatt.workers.dev/download',                     active: true },
      { name: 'LightDLMovies',      url: 'https://rentry.co/FMHYB64#lightdl',                                        active: true },
      { name: 'Vadapav',            url: 'https://rentry.co/FMHYB64#vadapav',                                         active: true },
      { name: 'Medeberiya',         url: 'https://medeberiya.net',                                                    active: true },
      { name: 'Downloader2',        url: 'https://downloader2.com',                                                   active: true },
      { name: "Ripper's Archive",   url: 'https://rentry.co/FMHYB64#rippers-archive',                                active: true },
      { name: 'KatMovieHD',         url: 'https://katworld.net/?type=KatmovieHD',                                     active: true },
      { name: 'HindMoviez',         url: 'https://hindmoviez.cafe',                                                   active: true },
      { name: 'Sinflix',            url: 'https://rentry.co/FMHYB64#sinflix',                                         active: true },
      { name: 'DramaSuki',          url: 'https://rentry.co/FMHYB64#dramasuki',                                       active: true },
      { name: 'KimoiTV',            url: 'https://kimoitv.com',                                                       active: true },
      { name: 'OlaMovies',          url: 'https://olamovies.dad',                                                     active: true },
      { name: 'PSArips',            url: 'https://psa.wf',                                                            active: true },
      { name: 'KiraStreams',         url: 'https://kirastreamsv3.vercel.app',                                          active: true },
      { name: 'isaiDub',            url: 'https://rentry.co/FMHYB64#isaidub',                                         active: true },
      { name: 'TVSeries',           url: 'https://www.tvseries.in',                                                   active: true },
      { name: 'StagaTV',            url: 'https://www.stagatv.com',                                                   active: true },
      { name: 'Cineby',             url: 'https://www.cineby.sc',                                    starred: true,  active: true },
      { name: 'Movies Ni Pipay',    url: 'https://moviesnipipay.me',                                                  active: true },
      { name: 'HDRush',             url: 'https://hdrush.cc',                                                         active: true },
      { name: 'RLSXTVT',            url: 'https://rlsxtvt.icu',                                                       active: true },
      { name: 'UHDMovies',          url: 'https://modlist.in/?type=uhdmovies',                                        active: true },
      { name: '4KHDHub',            url: 'https://4khdhub.link',                                                      active: true },
      { name: 'ShareSpark',         url: 'https://ww1.sharespark.cfd',                                                active: true },
      { name: 'TFPDL',              url: 'https://tfpdl.se/category/movies',                                          active: true },
      { name: 'Free Movies',        url: 'https://free-movies.to',                                                    active: true },
      { name: 'SeriesVault',        url: 'https://seriesvault.win',                                                   active: true },
      { name: 'FilmFans',           url: 'https://filmfans.org',                                                      active: true },
      { name: 'WorldFree4u',        url: 'https://worldfree4u.moe',                                                   active: true },
      { name: 'SSR Movies',         url: 'https://ssrmovies.com',                                                     active: true },
      { name: 'Best-MovieZ',        url: 'https://www.best-moviez.ws',                                                active: true },
      { name: 'SeriezLoaded NG',    url: 'https://www.seriezloaded.com.ng',                                           active: true },
      { name: 'ShareMania',         url: 'https://sharemania.us',                                                     active: true },
      { name: 'ShareBB',            url: 'https://sharebb.me',                                                        active: true },
      { name: 'FilmVault',          url: 'https://filmvault.xyz',                                    starred: true,  active: true },
      { name: 'Cinefy',             url: 'https://thecinefy.site',                                                    active: true },
      { name: 'nKiri',              url: 'https://nkiri.ink',                                                         active: true },
      { name: 'RareDoramas',        url: 'https://www.raredoramas.com',                                               active: true },
      { name: 'Toku.fun',           url: 'https://toku.fun',                                                          active: true },
      { name: 'HDEncode',           url: 'https://hdencode.org',                                                      active: true },
      { name: 'RapidMoviez',        url: 'https://rmz.cr',                                                            active: true },
    ],
  },
  {
    id: 'torrent-sites',
    title: 'Torrent Sites',
    fmhyUrl: 'https://fmhy.net/videopiracy#torrent-sites',
    tip: 'Use a VPN or seedbox. Check FMHY for the full list with ratings.',
    sites: [
      { name: 'YTS',              url: 'https://yts.bz',                                        active: true },
      { name: 'YifyMovies',       url: 'https://yifymovies.xyz',                                active: true },
      { name: '1337x',            url: 'https://1337x.to/movie-library/1', starred: true,       active: true },
      { name: 'RuTracker',        url: 'https://rutracker.org/forum/index.php?c=2', starred: true, active: true },
      { name: 'ExT',              url: 'https://ext.to',                   starred: true,       active: true },
      { name: 'Kinozal',          url: 'https://kinozal.tv',               starred: true,       active: true },
      { name: 'EZTV',             url: 'https://eztvx.to',                 starred: true,       active: true },
      { name: 'TPB',              url: 'https://thepiratebay.org/search.php?q=top100:200',      active: true },
      { name: 'LimeTorrents',     url: 'https://www.limetorrents.lol',                          active: true },
      { name: 'RARBGLite',        url: 'https://rarbglite.github.io',                           active: true },
      { name: 'Kontrast',         url: 'https://kontrast.top',                                  active: true },
      { name: 'Youplex Torrents', url: 'https://torrents.youplex.site',                         active: true },
      { name: 'Public Domain Torrents', url: 'https://www.publicdomaintorrents.info',           active: true },
    ],
  },
  {
    id: 'anime-torrent',
    title: 'Anime Torrenting',
    fmhyUrl: 'https://fmhy.net/videopiracy#anime-torrenting',
    tip: 'Quality anime torrents with subtitle options.',
    sites: [
      { name: 'Nyaa',            url: 'https://nyaa.si',                  starred: true,  active: true },
      { name: 'nekoBT',          url: 'https://nekobt.to',                                active: true },
      { name: 'TokyoTosho',      url: 'https://www.tokyotosho.info',                      active: true },
      { name: 'ShanaProject',    url: 'https://www.shanaproject.com',                     active: true },
      { name: 'bakabt',          url: 'https://bakabt.me',                                active: true },
      { name: 'SeaDex',          url: 'https://releases.moe',                             active: true },
      { name: 'Fansub Cartel',   url: 'https://index.fansubcar.tel',                      active: true },
    ],
  },
  {
    id: 'tracking',
    title: 'Tracking / Databases',
    fmhyUrl: 'https://fmhy.net/videopiracy#tracking-databases',
    tip: "Track what you've watched, get recommendations, and browse databases.",
    sites: [
      { name: 'Simkl',           url: 'https://simkl.com',               starred: true,  active: true },
      { name: 'Letterboxd',      url: 'https://letterboxd.com',          starred: true,  active: true },
      { name: 'ICheckMovies',    url: 'https://www.icheckmovies.com',    starred: true,  active: true },
      { name: 'Serializd',       url: 'https://www.serializd.com',       starred: true,  active: true },
      { name: 'Trakt',           url: 'https://trakt.tv',                                active: true },
      { name: 'IMDb',            url: 'https://www.imdb.com',                            active: true },
      { name: 'TMDb',            url: 'https://www.themoviedb.org',                      active: true },
      { name: 'JustWatch',       url: 'https://www.justwatch.com',                       active: true },
      { name: 'Rotten Tomatoes', url: 'https://www.rottentomatoes.com',                  active: true },
      { name: 'Kinorium',        url: 'https://en.kinorium.com',                         active: true },
      { name: 'Movieo',          url: 'https://movieo.me',                               active: true },
      { name: 'AllMovie',        url: 'https://www.allmovie.com',                        active: true },
      { name: 'Box Office Mojo', url: 'https://www.boxofficemojo.com',                   active: true },
      { name: 'MyDramaList',     url: 'https://mydramalist.com',                         active: true },
      { name: 'FlickMetrix',     url: 'https://flickmetrix.com',                         active: true },
      { name: 'uNoGS',           url: 'https://unogs.com',                               active: true },
    ],
  },
  {
    id: 'anime-tracking',
    title: 'Anime Tracking',
    fmhyUrl: 'https://fmhy.net/videopiracy#anime-tracking-databases',
    tip: 'Track anime and manga progress.',
    sites: [
      { name: 'MyAnimeList', url: 'https://myanimelist.net',  starred: true,  active: true },
      { name: 'AniList',     url: 'https://anilist.co',       starred: true,  active: true },
      { name: 'Kitsu',       url: 'https://kitsu.io',                         active: true },
      { name: 'AniDB',       url: 'https://anidb.net',                        active: true },
      { name: 'Anime-Planet',url: 'https://www.anime-planet.com',             active: true },
      { name: 'Anisearch',   url: 'https://www.anisearch.com',                active: true },
      { name: 'Taiga',       url: 'https://taiga.moe',                        active: true },
    ],
  },
  {
    id: 'subtitle-tools',
    title: 'Subtitle Tools',
    fmhyUrl: 'https://fmhy.net/videopiracy#subtitle-tools',
    tip: 'Download and manage subtitles for any content.',
    sites: [
      { name: 'OpenSubtitles', url: 'https://opensubtitles.org',             active: true },
      { name: 'Subscene',      url: 'https://sub-scene.com',                 active: true },
      { name: 'SubSource',     url: 'https://subsource.net',                 active: true },
      { name: 'SubDL',         url: 'https://subdl.com',                     active: true },
      { name: 'Addic7ed',      url: 'https://www.addic7ed.com',              active: true },
      { name: 'YifySubtitles', url: 'https://yifysubtitles.ch',              active: true },
      { name: 'Podnapisi',     url: 'https://www.podnapisi.net',             active: true },
      { name: 'Bazarr',        url: 'https://www.bazarr.media',              active: true },
      { name: 'kitsuneko',     url: 'https://kitsunekko.net',                active: true },
      { name: 'DownSub',       url: 'https://downsub.com',                   active: true },
      { name: 'SaveSubs',      url: 'https://www.savesubs.com',              active: true },
      { name: 'Subtitle Edit',  url: 'https://www.nikse.dk/subtitleedit',    active: true },
      { name: 'asbplayer',     url: 'https://killergerbah.github.io/asbplayer', active: true },
    ],
  },
]
